TpAspNet/Models/ErrorViewModel.cs
using System;

namespace TpAspNet.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TpAspNet/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TpAspNet.Models;
using App.Data.Services;


namespace TpAspNet.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly RestaurantsServices _services;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
            _services = new RestaurantsServices();

        }

        public IActionResult Index()
        {
            return View(_services.TopFive());
        }

        public IActionResult Privacy()        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TpAspNet/Controllers/RestaurantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using App.Data.DB;
using App.Data.Model;
using App.Data.Services;
using Microsoft.AspNetCore.Http;

namespace TpAspNet.Controllers
{
    public class RestaurantsController : Controller
    {
        private readonly RestaurantsServices _services;

        public RestaurantsController()
        {
            _services = new RestaurantsServices();
        }

        // GET: Restaurants
        public IActionResult Index()
        {
            return View(_services.getHome());
        }

        // GET: Restaurants/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restaurant = _services.getDetails(id);
            //var restaurant = await _context.Restaurants
                //.FirstOrDefaultAsync(m => m.id == id);
            if (restaurant == null)
            {
                return NotFound();
            }

            return View(restaurant);
        }

        // GET: Restaurants/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Restaurants/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(IFormCollection collection)
        {
            if (ModelState.IsValid)
            {
                var r = new Restaurant();
                r.name = collection["name"];
                r.phone = collection["phone"];
                r.comment = collection["comment"];
                r.email = collection["email"];
                r.note = new Note
                {
                    valueNote = int.Parse(collection["note.valueNote"])
                };
                r.address = new Address
                {
                    rue = collection["address.rue"],
                    CP = collection["address.CP"],
                    city = collection["address.city"]
                };
                _services.createAction(r);
                return RedirectToAction(nameof(Index));
            }
            return View(collection);
        }

        // GET: Restaurants/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restaurant =  _services.getEdit(id);

            if (restaurant == null)
            {
                return NotFound();
            }
            return View(restaurant);
        }

        // POST: Restaurants/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int? id, IFormCollection collection)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var r = _services.getDetails(id);
                    r.name = collection["name"];
                    r.phone = collection["phone"];
                    r.comment = collection["comment"];
                    r.email = collection["email"];
                    r.note = new Note 
                    { 
                        valueNote = int.Parse(collection["note.valueNote"]) 
                    };
                    r.address = new Address
                    {
                        rue = collection["address.rue"],
                        CP = collection["address.CP"],
                        city = collection["address.city"]
                    };
                    _services.editAction(r);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RestaurantExists((int)id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(_services.getDetails(id));
        }

        // GET: Restaurants/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restaurant = _services.getDetails(id);
            if (restaurant == null)
            {
                return NotFound();
            }

            return View(restaurant);
        }

        // POST: Restaurants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _services.deleteAction(id);
            return RedirectToAction(nameof(Index));
        }

        private bool RestaurantExists(int id)
        {
            return _services.restaurantExists(id);
        }
    }
}

TpAspNet/Views/Home/Index.cshtml
@model IEnumerable<App.Data.Model.Restaurant>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.phone)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.comment)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.note)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.phone)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.comment)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.address.rue) @Html.DisplayFor(modelItem => item.address.city) @Html.DisplayFor(modelItem => item.address.CP)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.note.valueNote)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

TpAspNet/Views/Restaurants/Create.cshtml
@model App.Data.Model.Restaurant

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Restaurant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="phone" class="control-label"></label>
                <input asp-for="phone" class="form-control" />
                <span asp-validation-for="phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="comment" class="control-label"></label>
                <input asp-for="comment" class="form-control" />
                <span asp-validation-for="comment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="address.rue" class="control-label"></label>
                <input asp-for="address.rue" class="form-control" />
                <span asp-validation-for="address.rue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="address.city" class="control-label"></label>
                <input asp-for="address.city" class="form-control" />
                <span asp-validation-for="address.city" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="address.CP" class="control-label"></label>
                <input asp-for="address.CP" class="form-control" />
                <span asp-validation-for="address.CP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="note.valueNote" class="control-label"></label>
                <input asp-for="note.valueNote" class="form-control" />
                <span asp-validation-for="note.valueNote" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TpAspNet/Views/Restaurants/Delete.cshtml
@model App.Data.Model.Restaurant

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Restaurant</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.comment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.comment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TpAspNet/Views/Restaurants/Details.cshtml
@model App.Data.Model.Restaurant

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Restaurant</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.comment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.comment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.email)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TpAspNet/Views/Restaurants/Edit.cshtml
@model App.Data.Model.Restaurant

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Restaurant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="phone" class="control-label"></label>
                <input asp-for="phone" class="form-control" />
                <span asp-validation-for="phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="comment" class="control-label"></label>
                <input asp-for="comment" class="form-control" />
                <span asp-validation-for="comment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="address.rue" class="control-label"></label>
                <input asp-for="address.rue" class="form-control" />
                <span asp-validation-for="address.rue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="address.city" class="control-label"></label>
                <input asp-for="address.city" class="form-control" />
                <span asp-validation-for="address.city" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="address.CP" class="control-label"></label>
                <input asp-for="address.CP" class="form-control" />
                <span asp-validation-for="address.CP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="note.valueNote" class="control-label"></label>
                <input asp-for="note.valueNote" class="form-control" />
                <span asp-validation-for="note.valueNote" class="text-danger"></span>
            </div>
            @*<div>
            <label asp-for="note.lastDate" class="control-label"></label>
            <input asp-for="note.lastDate" class="form-control" />
            <span asp-validation-for="note.lastDate" class="text-danger"></span>
        </div>
            <div class="form-group">
                <label asp-for="note.comment" class="control-label"></label>
                <input asp-for="note.comment" class="form-control" />
                <span asp-validation-for="note.comment" class="text-danger"></span>
            </div>
                *@
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
    </form>
</div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TpAspNet/Views/Restaurants/Index.cshtml
@model IEnumerable<App.Data.Model.Restaurant>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.comment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.note)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.comment)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.address.rue) @Html.DisplayFor(modelItem => item.address.city) @Html.DisplayFor(modelItem => item.address.CP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.note.valueNote)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

TpAspNet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TpAspNet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TpAspNet</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Restaurants" asp-action="Index">Restaurants</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TpAspNet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>